"""
Notifier Agent - Posts review report to GitHub PR.

Responsibilities:
1. Take report from state
2. Post report to GitHub PR as a comment
3. Output: notification_status, notification_url, notification_error
"""
import os
import sys
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.base_agent import BaseAgent
from tools.github_tool import GitHubTool, parse_pr_url
from graph.state import AgentState


class NotifierAgent(BaseAgent):
    """
    Agent that posts the review report to GitHub PR.
    
    Input state: report, pr_url, github_token
    Output state: notification_status, notification_url, notification_error
    """
    
    def __init__(self, name: str = "notifier"):
        super().__init__(name)
    
    async def run(self, state: AgentState) -> Dict[str, Any]:
        """
        Post review report to GitHub PR.
        
        Args:
            state: Current workflow state with report and pr_url
            
        Returns:
            Updated state with notification results
        """
        self.logger.info("[NotifierAgent] Posting review to GitHub PR...")
        
        try:
            report_data = state.get("report")
            pr_url = state.get("pr_url", "")
            github_token = state.get("github_token", "")
            
            if not report_data:
                return {
                    "notification_status": "failed",
                    "notification_error": "No report to post",
                    "current_step": "notifier_error",
                }
            
            # Parse PR URL
            owner, repo, pr_number = parse_pr_url(pr_url)
            
            # Create GitHub tool
            github_tool = GitHubTool(token=github_token)
            
            # Prepare comment body (Markdown report)
            report_markdown = report_data.get("report_markdown", "")
            comment_body = f"""## 🤖 AI Code Review (Generated by CodeAgent Reviewer)

{report_markdown}

---
*This review was automatically generated by [CodeAgent Reviewer](https://github.com/yourusername/code-review-agent).*
"""
            
            # Post review comment to PR
            result = github_tool.post_review_comment(owner, repo, pr_number, comment_body)
            
            self.logger.info(f"[NotifierAgent] Posted review to PR: {result.get('html_url', 'N/A')}")
            
            return {
                "notification_status": "posted",
                "notification_url": result.get("html_url", ""),
                "notification_error": None,
                "current_step": "notifier_done",
            }
            
        except Exception as e:
            self.logger.error(f"[NotifierAgent] Error: {e}", exc_info=True)
            return {
                "notification_status": "failed",
                "notification_error": str(e),
                "current_step": "notifier_error",
            }
